SLING-10299 : Allow for removal of access control policies (not just individual entries)
apache/sling-org-apache-sling-repoinit-parser pull request #10
Opened 2021-05-05 12:54 UTC by anchela

@bdelacretaz , @cziegeler , i would appreciate if you had time to review the proposed extension of the repoinit-parser.

2021-05-05 13:54 UTC, cziegeler approved these changes
Lgtm, thanks

2021-05-05 14:10 UTC, bdelacretaz requested changes
Looks good to me with three minor comments, add @ProviderType to the operations. Thank you!

2021-05-05 14:10 UTC, bdelacretaz commented on src/main/java/org/apache/sling/repoinit/parser/operations/DeleteAclPaths.java
> +public class DeleteAclPaths extends Operation {
Operations should be @ProviderType to avoid too strict restrictions on package version numbers

2021-05-05 14:10 UTC, bdelacretaz commented on src/main/java/org/apache/sling/repoinit/parser/operations/DeleteAclPrincipalBased.java
> +public class DeleteAclPrincipalBased extends Operation {
Also need @ProviderType here

2021-05-05 14:10 UTC, bdelacretaz commented on src/main/java/org/apache/sling/repoinit/parser/operations/DeleteAclPrincipals.java
> +public class DeleteAclPrincipals extends Operation {
Also need @ProviderType here

2021-05-05 14:12 UTC, bdelacretaz commented
Ah, and one more thing, the `org.apache.sling.repoinit.language` value needs to be incremented in `bnd.bnd` to indicate that the language has evolved.

2021-05-05 15:24 UTC, anchela commented on src/main/java/org/apache/sling/repoinit/parser/operations/DeleteAclPaths.java
> +public class DeleteAclPaths extends Operation {
ah sure.... i missed that.

2021-05-05 15:29 UTC, anchela commented on src/main/java/org/apache/sling/repoinit/parser/operations/DeleteAclPrincipals.java
> +public class DeleteAclPrincipals extends Operation {
done

2021-05-05 15:29 UTC, anchela commented on src/main/java/org/apache/sling/repoinit/parser/operations/DeleteAclPrincipalBased.java
> +public class DeleteAclPrincipalBased extends Operation {
done

2021-05-05 15:32 UTC, anchela commented
@bdelacretaz , one more question for you: since _OperationVisitor_ is defined as ConsumerType adding new methods would have resulted in a major version change. is adding the 3 new visit-methods with default impl the right way? i was wondering why other methods introduced later on didn't have that.

2021-05-05 16:06 UTC, bdelacretaz commented
I think adding default methods to _OperationVisitor_  like you did is great, not sure why we didn't do that for earlier changes.

2021-05-05 16:31 UTC, anchela commented
@bdelacretaz, anything else from your side? maybe you want to look at the implementation in jcr-repo-init. at least for me that sometimes helps spotting additional things that are not that obvious when just looking at the parser.

2021-05-06 11:30 UTC, anchela commented
@bdelacretaz , it would be good if you could take another look. i would like to merge it in order not to have too many different PR floating around to keep in mind.

2021-05-07 10:07 UTC, bdelacretaz commented on src/main/javacc/RepoInitGrammar.jjt
> +void removeAclPaths(List<Operation> result) :
I missed this in a previous review: as we changed the syntax to use delete instead of remove, these productions should also be called delete* instead of remove*, for clarity.

2021-05-07 10:09 UTC, bdelacretaz commented
Apart from my (minor) last comment above this PR looks good to me, thank you!

I won't have time to look at the JCR side of things right now, probably not before ten days.

2021-05-07 12:14 UTC, anchela commented on src/main/javacc/RepoInitGrammar.jjt
> +void removeAclPaths(List<Operation> result) :
done

2021-05-07 12:17 UTC, anchela commented
> I won't have time to look at the JCR side of things right now, probably not before ten days.

well..... that's unfortunate, because we can't resolve the issue.... in particular since there is no separate component for repo-init-parser vs repo-init-jcr... in addition just adjusting the parse is of no use if there is no implementation. it just adds  additional language options that cannot be used (as this happened multiple times in the past). i will see if someone else in the sling team is willing to review it.

2021-05-07 12:18 UTC, anchela commented
@bdelacretaz , please confirm that all findings have been addressed such that we can at least merge this piece for now.

2021-05-07 14:38 UTC, karlpauls approved these changes

2021-05-07 14:53 UTC, bdelacretaz approved these changes

2021-05-07 14:55 UTC, bdelacretaz commented
FYI when I said "I won't have time to look at the JCR side of things right now" I mean I don't have time to _implement_ that right now. If someone has time to do that I'll find time to review.

> in particular since there is no separate component for repo-init-parser vs repo-init-jcr...

Not sure what you mean, if that's a JIRA component I'm +1 on creating separate ones if that helps.

2021-05-07 15:06 UTC, anchela commented
@bdelacretaz , i already implemented the JCR-repoinit part :) i pinged you for a review at https://github.com/apache/sling-org-apache-sling-jcr-repoinit/pull/16

2021-05-07 15:19 UTC, bdelacretaz commented
> i already implemented the JCR-repoinit part...

Ah sorry, that's what I missed! I'll have a look in the next two hours.

2021-05-07 15:24 UTC, merged